'use client'

import {
  User,
  Phone,
  MapPin,
  Receipt,
  ShieldCheck,
  Calendar,
  AlertTriangle,
} from 'lucide-react'
import { Card, CardContent } from '@/components/ui/card'
import { cn } from '@/lib/utils'
import type { ClientInfo, ClientSummary } from '../types'
import { roleStyles, type ClientRole } from '../constants'

interface ClientProfileProps {
  client: ClientInfo
  summary: ClientSummary
}

// Check if clientCode looks like an auto-generated ID (too long to display)
function isAutoGeneratedId(code: string | null | undefined): boolean {
  if (!code) return true
  // If code is longer than 15 chars, it's likely an auto-generated ID (cuid, uuid, etc.)
  return code.length > 15
}

export function ClientProfile({ client, summary }: ClientProfileProps) {
  const roles: string[] = []
  if (summary.hasBeenClient) roles.push('Cliente')
  if (summary.hasBeenCollateral) roles.push('Aval')

  const primaryPhone = client.phones?.[0]
  const showClientCode = !isAutoGeneratedId(client.clientCode)

  return (
    <Card className="mb-4">
      <CardContent className="p-3 space-y-3">
        {/* Client Header */}
        <div className="flex items-start gap-3">
          <div className="rounded-full p-2 bg-primary/10 flex-shrink-0">
            <User className="h-5 w-5 text-primary" />
          </div>
          <div className="flex-1 min-w-0">
            <div className="font-semibold text-sm truncate">{client.fullName}</div>
            <div className="flex items-center gap-2 text-xs text-muted-foreground mt-0.5">
              {showClientCode && (
                <span className="font-mono">{client.clientCode}</span>
              )}
              <span className="flex items-center gap-0.5">
                <Phone className="h-3 w-3" />
                {primaryPhone || 'Sin tel.'}
              </span>
            </div>
            <div className="flex gap-1 mt-1">
              {roles.map((role) => (
                <span
                  key={role}
                  className={cn(
                    'text-[9px] px-1.5 py-0.5 rounded font-medium',
                    roleStyles[role as ClientRole]
                  )}
                >
                  {role}
                </span>
              ))}
            </div>
          </div>
        </div>

        {/* Leader Info */}
        {client.leader && (
          <div className="text-xs px-2 py-1.5 rounded-md bg-muted/60 border">
            <div className="flex items-center gap-1.5">
              <span className="text-[10px] font-semibold text-muted-foreground uppercase">Líder:</span>
              <span className="font-medium truncate">{client.leader.name}</span>
            </div>
            <div className="flex items-center gap-2 text-[10px] text-muted-foreground mt-0.5">
              {client.leader.location && (
                <span className="font-medium text-foreground">{client.leader.location}</span>
              )}
              <span className="flex items-center gap-1">
                <MapPin className="h-3 w-3" />
                <span>{client.leader.route}</span>
              </span>
            </div>
          </div>
        )}

        {/* Stats Grid - 2x2 on mobile */}
        <div className="grid grid-cols-2 gap-2">
          <div className="flex items-center gap-2 p-2 rounded-lg bg-muted/50">
            <Receipt className="h-4 w-4 text-primary flex-shrink-0" />
            <div className="min-w-0">
              <div className="text-xs font-bold">
                {summary.totalLoansAsClient}
                {summary.activeLoansAsClient > 0 && (
                  <span className="text-success ml-1">({summary.activeLoansAsClient} activo)</span>
                )}
              </div>
              <div className="text-[10px] text-muted-foreground">préstamos</div>
            </div>
          </div>

          <div className="flex items-center gap-2 p-2 rounded-lg bg-muted/50">
            <ShieldCheck className="h-4 w-4 text-info flex-shrink-0" />
            <div className="min-w-0">
              <div className="text-xs font-bold">{summary.totalLoansAsCollateral}</div>
              <div className="text-[10px] text-muted-foreground">aval</div>
            </div>
          </div>

          <div className="flex items-center gap-2 p-2 rounded-lg bg-muted/50">
            <Calendar className="h-4 w-4 text-muted-foreground flex-shrink-0" />
            <div className="min-w-0">
              <div className="text-xs font-bold truncate">
                {summary.firstLoanDate
                  ? new Date(summary.firstLoanDate).toLocaleDateString('es-MX', {
                      month: 'short',
                      year: 'numeric',
                    })
                  : 'N/A'}
              </div>
              <div className="text-[10px] text-muted-foreground">cliente desde</div>
            </div>
          </div>

          <div className="flex items-center gap-2 p-2 rounded-lg bg-muted/50">
            <AlertTriangle className={cn(
              'h-4 w-4 flex-shrink-0',
              summary.avgMissedPaymentsPerLoan > 2 ? 'text-destructive' :
              summary.avgMissedPaymentsPerLoan > 0 ? 'text-warning' : 'text-success'
            )} />
            <div className="min-w-0">
              <div className={cn(
                'text-xs font-bold',
                summary.avgMissedPaymentsPerLoan > 2 ? 'text-destructive' :
                summary.avgMissedPaymentsPerLoan > 0 ? 'text-warning' : 'text-success'
              )}>
                {summary.avgMissedPaymentsPerLoan}
              </div>
              <div className="text-[10px] text-muted-foreground">faltas prom.</div>
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  )
}
